try:
    print(1/0)
    # print(num)
except Exception as result:
    print(result)